AllCops:
  TargetRubyVersion: 3.1.0

  NewCops: disable
  Exclude:
    - 'Brewfile'
    - 'vendor/bundle/**/*'  # Prevent RuboCop pulling in .rubocop.yml files from vendor directories in GitHub Actions: https://github.com/rubocop/rubocop/issues/9832

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
