name: Tests

on:
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Ruby
      uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
      with:
        bundler-cache: true
    - name: Run tests and rubocop
      run: bundle exec rake
